name: Develop to Release PR and Tag

on:
  push:
    branches:
      - develop

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Promote Develop to Release"
          pr_body: "This is an automated PR to promote changes from develop to release."
          pr_label: "automate-pr"
          destination_branch: "release"
          source_branch: "develop"

  create_tag:
    needs: create_pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures tags are fetched

      - name: Create Tag
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true  # Prefix the tag with 'v'. Set to false to omit.
          DEFAULT_BUMP: minor  # Default to 'minor' version bump. Other options: 'major', 'minor', 'patch'
          RELEASE_BRANCHES: release  # Only creates a tag if the branch is 'release'
          DRY_RUN: false  # Set to true to simulate the action without making any changes
