name: Automate PR from Develop to Release

on:
  push:
    branches:
      - develop

jobs:
  create_pr_to_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Garante que todas as tags sejam buscadas

      - name: Get Latest Tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0)
          echo "::set-output name=tag::$latest_tag"

      - name: Check if Tag Exists
        run: |
          if git tag | grep -q "${{ steps.get_tag.outputs.tag }}"; then
            echo "Tag ${{ steps.get_tag.outputs.tag }} already exists. Incrementing version."
            # Incrementa a versão para a próxima
            current_version=${{ steps.get_tag.outputs.tag }}
            next_version=$(echo $current_version | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
            echo "Next version: $next_version"
          else
            echo "Tag ${{ steps.get_tag.outputs.tag }} does not exist. Creating a new tag."
            next_version="${{ steps.get_tag.outputs.tag }}"
          fi

      - name: Create Tag and Push
        run: |
          git tag $next_version
          git push origin $next_version

      - name: Create Release Branch
        run: |
          next_version="${{ steps.get_tag.outputs.tag }}"
          branch_name="release/$next_version"
          git checkout -b $branch_name $next_version
          git push origin $branch_name

      - name: Create Pull Request to Release
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Merge Develop into Release"
          pr_body: "Automated PR to merge changes from develop to release."
          pr_label: "automated-pr"
          destination_branch: "release/$next_version"
          source_branch: "develop"
