name: Feature to Develop PR

on:
  push:
    branches:
      - 'feature/*'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Automated PR: Merging ${{ github.ref }} into develop"
          pr_body: "This is an automated pull request to merge changes from ${{ github.ref }} into develop."
          pr_label: "automated-pr"
          destination_branch: "develop"
          source_branch: "${{ github.ref_name }}"
